# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "Shap": "01_shap.ipynb"}

modules = ["core.py",
           "mli.py"]

doc_url = "https://vochicong.github.io/kowaza/"

git_url = "https://github.com/vochicong/kowaza/tree/master/"

def custom_doc_links(name): return None
